# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RptDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('host', models.CharField(max_length=40)),
                ('port', models.CharField(max_length=20)),
                ('dbname', models.CharField(blank=True, max_length=40, null=True)),
                ('describe', models.CharField(blank=True, max_length=100, null=True)),
                ('extention_a', models.CharField(blank=True, max_length=100, null=True)),
                ('extention_b', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rptdatasource',
            },
        ),
        migrations.CreateModel(
            name='RptQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=40, unique=True)),
                ('author', models.CharField(max_length=40)),
                ('department', models.CharField(blank=True, max_length=40, null=True)),
                ('query_code', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'rptquery',
            },
        ),
        migrations.CreateModel(
            name='RptUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('role_code', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'rptuser',
            },
        ),
    ]
